ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/icm206xx-acc-new
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/gyroscope/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include

obj-y   :=  icm206xx_gyro.o

