# In case the platform does NOT support this type of sensors
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
obj-y   +=  alsps.o
obj-y   +=  alsps_factory.o
obj-y   +=  aal_control.o

obj-$(CONFIG_MTK_ALSPSHUB)        +=  alspshub/
obj-$(CONFIG_MTK_CM36558)         +=  cm36558/
obj-$(CONFIG_MTK_STK3X1X_NEW)   +=  stk3x1x-new/
obj-$(CONFIG_MTK_STK3338)       +=  stk3338/
obj-$(CONFIG_MTK_STK3410_NEW)   +=  stk3410-new/
obj-$(CONFIG_MTK_EPL2182_NEW)	  +=  EPL2182-new/
obj-$(CONFIG_MTK_EPL259X_NEW)   +=  epl259x-new/
obj-$(CONFIG_MTK_EPL89XX_NEW)   +=  epl89xx-new/
obj-$(CONFIG_MTK_TMD277X_NEW)   +=  tmd277x-new/
obj-$(CONFIG_MTK_CM36558)       +=  cm36558/
